version: '2.4'

services:
  auth-service:
    build:
      context: ../
      dockerfile: ./docker/php-fpm/Auth/Dockerfile
    volumes:
      - ../AuthService:/auth
      - ../JsonSchemes:/auth/JsonSchemes

  task-tracker-service:
    build:
      context: ../
      dockerfile: ./docker/php-fpm/Task/Dockerfile
    volumes:
      - ../TaskTrackerService:/task
      - ../JsonSchemes:/task/JsonSchemes

  #Nginx Service
  webserver:
    image: nginx:1.17.9-alpine
    volumes:
      - ../AuthService:/auth
      - ../TaskTrackerService:/task
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${NGINX_PORT}:80"

  postgresql-auth-master:
    image: 'bitnami/postgresql:latest'
    volumes:
      - 'postgresql_auth_master_data:/bitnami/postgresql'
    environment:
      POSTGRESQL_USERNAME: ${POSTGRESQL_AUTH_USERNAME}
      POSTGRESQL_PASSWORD: ${POSTGRESQL_AUTH_PASSWORD}
      POSTGRESQL_DATABASE: ${POSTGRESQL_AUTH_DATABASE}
    ports:
      - '${POSTGRESQL_AUTH_PORT}:5432'

  postgresql-task-master:
    image: 'bitnami/postgresql:latest'
    volumes:
      - 'postgresql_task_master_data:/bitnami/postgresql'
    environment:
      POSTGRESQL_USERNAME: ${POSTGRESQL_TASK_USERNAME}
      POSTGRESQL_PASSWORD: ${POSTGRESQL_TASK_PASSWORD}
      POSTGRESQL_DATABASE: ${POSTGRESQL_TASK_DATABASE}
    ports:
      - '${POSTGRESQL_TASK_PORT}:5432'

  redis:
    image: "redis:alpine"
    sysctls:
      net.core.somaxconn: 1024

  # брокер сообщений
  rabbitmq:
    image: 'rabbitmq:3.9.7-management-alpine'
    ports:
      - '${RABBITMQ_PORT}:15672'


volumes:
  postgresql_auth_master_data:
  postgresql_task_master_data: