version: '2.4'

services:
  app:
    build:
      context: ../
      dockerfile: ./docker/php-fpm/Dockerfile
    volumes:
      - ../App:/application

  #Nginx Service
  webserver:
    image: nginx:1.17.9-alpine
    working_dir: /application
    volumes:
      - ../App:/application
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${NGINX_PORT}:80"

  pgbouncer-writer:
    image: edoburu/pgbouncer
    environment:
      - DB_USER=${POSTGRESQL_USERNAME}
      - DB_PASSWORD=${POSTGRESQL_PASSWORD}
      - DB_HOST=postgresql-master
      - DB_NAME=${POSTGRESQL_DATABASE}
      - POOL_MODE=transaction
      - ADMIN_USERS=${POSTGRESQL_USERNAME}
    ports:
      - '${PGBOUNCER_WRITER_PORT}:5432'
    depends_on:
      - postgresql-master


  postgresql-master:
    image: 'bitnami/postgresql:latest'
    volumes:
      - 'postgresql_master_data:/bitnami/postgresql'
    environment:
      POSTGRESQL_USERNAME: ${POSTGRESQL_USERNAME}
      POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRESQL_DATABASE: ${POSTGRESQL_DATABASE}


  redis:
    image: "redis:alpine"
    sysctls:
      net.core.somaxconn: 1024


  # брокер сообщений
  rabbitmq:
    image: 'rabbitmq:3.9.7-management-alpine'
    ports:
      - '${RABBITMQ_PORT}:15672'


volumes:
  postgresql_master_data: